# Generated by Django 5.2.7 on 2026-06-12 13:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apartments', '0002_alter_apartment_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='apartment',
            name='property_type',
            field=models.CharField(choices=[('flat', 'Flat'), ('commercial', 'Commercial'), ('plot', 'Open Plot'), ('industrial', 'Industrial Gala')], default='flat', max_length=20),
        ),
    ]
